name: add_pr_comment
on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: get-comment-body
        run: |
          body="$(cat comment-body.txt)"
          body="$(body//'%'/'%25'}"
          body="$(body//%'\n'/'%0A'}"
          body="$(body//%'\r'/'%0A'}"
        echo "::set-output name=body::$body"

      - name: Set comment
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-author: 'github-action[bot]'

