# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download cli tool
        run: wget https://phylum-cli.s3.us-east-2.amazonaws.com/phylum-cli-linux-v0.0.4.1-static.zip

      - name: Download phylum-js-submit
        run: git clone https://github.com/peterjmorgan/phylum-js-submit

      - name: Install phylum-js-submit deps
        run: |
          pushd phylum-js-submit || exit 1
            npm install
            export PATH=$PWD:$PATH
            echo "[*] installed phylum-js-submit"
          popd

      - name: Untar and install binary
        run: |
          unzip phylum-cli-linux-v0.0.4.1-static.zip
          export PATH="$PWD/phylum-cli-linux-v0.0.4-static-installer:$PATH"
          pushd phylum-cli-linux-v0.0.4-static-installer || exit 1
            bash install.sh
          popd
          echo "[*] installed phylum-cli"
      - name: Configure phylum-cli with credentials
        run: |
          sed -i "s/user:/user: ${{ secrets.PHYLUM_USER }}/" ~/.phylum/settings.yaml
          sed -i "s/pass:/pass: ${{ secrets.PHYLUM_PASS }}/" ~/.phylum/settings.yaml
          echo "[*] Configured phylum-cli with credentials"

      - name: Submit to API
        run: |
          export PATH="$HOME/.phylum:$PATH"
          export PATH=/home/runner/work/phylum-demo/phylum-demo/phylum-js-submit:$PATH
          ls
          pushd $GITHUB_WORKSPACE || exit 1
            phylum-cli init -p 'phylum-demo'
            phylum-js-submit.js -t package package-lock.json | egrep -o '[0-9a-f-]{36}' >> job_id
            cat job_id | xargs -I {} phylum-cli status -i {} | tail -n+2 > ~/results.json
          popd

      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ~/results.json

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Run python report
        run: |
          python -m pip install --upgrade pip setuptools wheel
          git clone https://github.com/peterjmorgan/phylum-python-report
          pushd phylum-python-report || exit 1
          if [ -f requirements.txt ];then
            echo "[*] python: installing requirements.txt"
            pip install -r requirements.txt
          fi
          python phylum-python-report.py ~/results.json > ~/report.txt

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ~/report.txt








