name: add_pr_comment
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
						Software Vulnerabilites
						====

						|Package Name|High|Medium|Low|
					  | :---: | :---: | :---: | :---: |
						|axios|1|0|0|
						|ini|0|0|1|

          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'Phylum[bot]'

